[build]
  command = "npm run dev"  # Command to build your project, adjust as per your setup
  functions = "netlify/functions"  # Folder where Netlify functions are located
  publish = "build"  # Folder with the static content for deployment

# Redirects configuration
[[redirects]]
  from = "/api/*"  # Redirect all requests starting with /api/
  to = "/.netlify/functions/mydata"  # Redirect to your Netlify function endpoint
  status = 200  # HTTP status code for the redirect

# Redirect for Single Page Applications (SPA)
[[redirects]]
  from = "/*"  # Redirect all unmatched routes (SPA fallback)
  to = "/index.html"  # Redirect to your index.html or SPA entry point
  status = 200  # HTTP status code for the redirect
